baseURL = "https://layer3logic.com/"
languageCode = "en-us"
title = "Layer 3 Logic"

theme     = "hugo-bootstrap-theme"
themesdir = "node_modules/@filipecarneiro"

# Main navigation
[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
  [[menu.main]]
    name   = "Services"
    url    = "/#services"
    weight = 2
  [[menu.main]]
    name   = "About"
    url    = "/#about"
    weight = 3
  [[menu.main]]
    name   = "Resources"
    url    = "/posts/"
    weight = 4
  [[menu.main]]
    name   = "Get Connected"
    url    = "/#contact"
    weight = 5

  # Social links for the footer/header
  [[menu.social]]
    name   = "LinkedIn"
    url    = "https://www.linkedin.com/company/layer3logic/"
    weight = 1

# Site parameters
[params]
  description = "Layer 3 Logic delivers expert IT system architecture, security consulting and procurement services for modern businesses."
  copyright   = "© 2025 Layer 3 Logic"

# Make params.social a table, not an array
[params.social]
  facebook_admin = ""   # leave blank if unused
